import Foundation

public enum Catalog {
    public static let ingredients: [Ingredient] = [
        .init("gin", "Gin", .spirits), .init("bourbon", "Bourbon", .spirits, aliases: ["bourbon whiskey"]),
        .init("rye", "Rye whiskey", .spirits, aliases: ["rye"]), .init("rum", "White rum", .spirits, aliases: ["light rum"]),
        .init("dark-rum", "Dark rum", .spirits), .init("tequila", "Blanco tequila", .spirits, aliases: ["tequila", "silver tequila"]),
        .init("vodka", "Vodka", .spirits), .init("brandy", "Brandy", .spirits, aliases: ["cognac"]),
        .init("campari", "Campari", .liqueurs), .init("aperol", "Aperol", .liqueurs),
        .init("sweet-vermouth", "Sweet vermouth", .liqueurs, aliases: ["red vermouth"]),
        .init("dry-vermouth", "Dry vermouth", .liqueurs),
        .init("triple-sec", "Orange liqueur", .liqueurs, aliases: ["triple sec", "cointreau"]),
        .init("coffee-liqueur", "Coffee liqueur", .liqueurs, aliases: ["kahlua", "kahlúa"]),
        .init("maraschino", "Maraschino liqueur", .liqueurs, aliases: ["maraschino"]),
        .init("violette", "Crème de violette", .liqueurs, aliases: ["creme de violette", "violet liqueur"]),
        .init("green-chartreuse", "Green Chartreuse", .liqueurs),
        .init("mure", "Crème de mûre", .liqueurs, aliases: ["creme de mure", "blackberry liqueur"]),
        .init("fernet", "Fernet-Branca", .liqueurs, aliases: ["fernet branca"]),
        .init("lillet-blanc", "Lillet Blanc", .liqueurs),
        .init("absinthe", "Absinthe", .spirits),
        .init("prosecco", "Prosecco", .mixers, aliases: ["sparkling wine"]),
        .init("lemon", "Lemon juice", .citrus, aliases: ["lemon", "lemons"]),
        .init("lime", "Lime juice", .citrus, aliases: ["lime", "limes"]),
        .init("orange", "Orange juice", .citrus), .init("grapefruit", "Grapefruit juice", .citrus),
        .init("cranberry", "Cranberry juice", .citrus),
        .init("syrup", "Simple syrup", .mixers, aliases: ["sugar syrup", "simple"]),
        .init("honey-syrup", "Honey syrup", .mixers), .init("agave", "Agave syrup", .mixers, aliases: ["agave nectar"]),
        .init("raspberry-syrup", "Raspberry syrup", .mixers),
        .init("soda", "Soda water", .mixers, aliases: ["club soda", "seltzer", "sparkling water"]),
        .init("tonic", "Tonic water", .mixers, aliases: ["tonic"]),
        .init("ginger-beer", "Ginger beer", .mixers), .init("cola", "Cola", .mixers, aliases: ["coke"]),
        .init("espresso", "Espresso", .mixers),
        .init("angostura", "Angostura bitters", .bitters, aliases: ["angostura", "aromatic bitters"]),
        .init("orange-bitters", "Orange bitters", .bitters), .init("mint", "Mint", .bitters, aliases: ["fresh mint"]),
        .init("basil", "Basil", .bitters, aliases: ["fresh basil"]),
        .init("egg-white", "Pasteurized egg white", .bitters, aliases: ["egg white", "egg whites", "pasteurized egg whites"]),
        .init("aquafaba", "Aquafaba", .bitters, aliases: ["chickpea brine"])
    ]

    public static func name(for id: String) -> String { ingredients.first { $0.id == id }?.name ?? id }

    private static func recipe(_ id: String, _ name: String, _ subtitle: String, _ family: String,
                               _ glass: String, _ color: String, _ ingredients: [RecipeIngredient],
                               _ steps: [String], garnish: String? = nil, variations: [Variation] = []) -> Recipe {
        Recipe(id: id, name: name, subtitle: subtitle, family: family, glass: glass, color: color,
               ingredients: ingredients, steps: steps, garnish: garnish, variations: variations)
    }

    private static let shake = ["Add the ingredients to a shaker filled with ice.", "Shake hard for 10–15 seconds, until the shaker feels cold.", "Strain into a chilled coupe."]
    private static let stir = ["Add the ingredients to a mixing glass filled with ice.", "Stir for 20–30 seconds until cold and lightly diluted.", "Strain into a chilled coupe."]
    private static let highball = ["Fill a highball glass with ice.", "Add the ingredients, pouring the fizzy mixer last.", "Stir gently to combine."]

    public static let recipes: [Recipe] = [
        recipe("old-fashioned", "Old Fashioned", "Rich whiskey, a little sugar, a little spice.", "Whiskey", "Rocks", "amber",
               [.init("bourbon", 60, imperial: .oz(2)), .init("syrup", 7.5, imperial: .oz(0.25)), .init("angostura", 2, .dash)],
               ["Add bourbon, simple syrup, and bitters to a rocks glass.", "Add a large ice cube and stir for 20–30 seconds."],
               garnish: "Express an orange peel over each glass.", variations: [
                Variation(id: "sweeter", name: "A little sweeter", note: "Use the increased syrup amount below for a sweeter drink. Taste before adding more.", ingredients: [.init("bourbon", 60, imperial: .oz(2)), .init("syrup", 12.5, imperial: .oz(0.5)), .init("angostura", 2, .dash)]),
                Variation(id: "orange", name: "Orange bitters", note: "Swap aromatic bitters for orange bitters for a brighter, less spicy drink.", ingredients: [.init("bourbon", 60, imperial: .oz(2)), .init("syrup", 7.5, imperial: .oz(0.25)), .init("orange-bitters", 2, .dash)]),
                Variation(id: "rye", name: "Rye Old Fashioned", note: "Use rye whiskey instead of bourbon for a drier, spicier drink.", ingredients: [.init("rye", 60, imperial: .oz(2)), .init("syrup", 7.5, imperial: .oz(0.25)), .init("angostura", 2, .dash)], steps: ["Add rye whiskey, simple syrup, and bitters to a rocks glass.", "Add a large ice cube and stir for 20–30 seconds."])]),
        recipe("negroni", "Negroni", "Bitter, bold, beautifully balanced.", "Gin", "Rocks", "red",
               [.init("gin", 30, imperial: .oz(1)), .init("campari", 30, imperial: .oz(1)), .init("sweet-vermouth", 30, imperial: .oz(1))],
               ["Add all ingredients to a rocks glass filled with ice.", "Stir for 20–30 seconds until cold."], garnish: "Add an orange peel to each glass."),
        recipe("margarita", "Margarita", "Bright lime meets agave and orange.", "Tequila", "Coupe", "lime",
               [.init("tequila", 50, imperial: .oz(2)), .init("triple-sec", 25, imperial: .oz(1)), .init("lime", 25, imperial: .oz(1))], shake,
               garnish: "Rub lime around half the rim and dip in salt before pouring.", variations: [
                Variation(id: "sweeter", name: "Soften the citrus", note: "Add the agave syrup listed below to round out the lime.", ingredients: [.init("tequila", 50, imperial: .oz(2)), .init("triple-sec", 25, imperial: .oz(1)), .init("lime", 25, imperial: .oz(1)), .init("agave", 5, imperial: .tsp(1))])]),
        recipe("daiquiri", "Daiquiri", "Three ingredients. Nothing to hide.", "Rum", "Coupe", "lime",
               [.init("rum", 60, imperial: .oz(2)), .init("lime", 25, imperial: .oz(0.75)), .init("syrup", 15, imperial: .oz(0.5))], shake, variations: [
                Variation(id: "dry", name: "A touch drier", note: "Use the reduced syrup amount below for a sharper finish.", ingredients: [.init("rum", 60, imperial: .oz(2)), .init("lime", 25, imperial: .oz(0.75)), .init("syrup", 10, imperial: .oz(0.25))])]),
        recipe("whiskey-sour", "Whiskey Sour", "A bright, silky whiskey classic.", "Whiskey", "Rocks", "amber",
               [.init("bourbon", 60, imperial: .oz(2)), .init("lemon", 30, imperial: .oz(1)), .init("syrup", 20, imperial: .oz(0.75))],
               ["Add all ingredients to a shaker with ice.", "Shake hard for 10–15 seconds.", "Strain into a rocks glass over fresh ice."], garnish: "Add a lemon slice or cocktail cherry. This version is made without egg white.", variations: [
                Variation(id: "rye", name: "Rye Whiskey Sour", note: "Use rye whiskey instead of bourbon for a spicier sour with a drier finish.", ingredients: [.init("rye", 60, imperial: .oz(2)), .init("lemon", 30, imperial: .oz(1)), .init("syrup", 20, imperial: .oz(0.75))])]),
        recipe("gin-sour", "Gin Sour", "Crisp botanicals with fresh lemon.", "Gin", "Coupe", "lemon",
               [.init("gin", 60, imperial: .oz(2)), .init("lemon", 30, imperial: .oz(1)), .init("syrup", 20, imperial: .oz(0.75))], shake),
        recipe("bees-knees", "Bee’s Knees", "Floral honey and a lemon lift.", "Gin", "Coupe", "lemon",
               [.init("gin", 60, imperial: .oz(2)), .init("lemon", 25, imperial: .oz(0.75)), .init("honey-syrup", 20, imperial: .oz(0.75))], shake,
               garnish: "Add a lemon twist. Use honey syrup made with equal parts honey and water."),
        recipe("gimlet", "Fresh Lime Gimlet", "Clean, tart, and botanical.", "Gin", "Coupe", "lime",
               [.init("gin", 60, imperial: .oz(2)), .init("lime", 25, imperial: .oz(0.75)), .init("syrup", 20, imperial: .oz(0.75))], shake, garnish: "Add a lime wheel."),
        recipe("tom-collins", "Tom Collins", "Tall, sparkling, lemony refreshment.", "Gin", "Highball", "lemon",
               [.init("gin", 45, imperial: .oz(1.5)), .init("lemon", 30, imperial: .oz(1)), .init("syrup", 15, imperial: .oz(0.5)), .init("soda", 90, imperial: .oz(3))],
               ["Shake gin, lemon juice, and simple syrup with ice.", "Strain into a tall glass filled with fresh ice.", "Add soda water and stir gently."], garnish: "Add a lemon wheel."),
        recipe("gin-tonic", "Gin & Tonic", "A crisp, bittersweet standby.", "Gin", "Highball", "clear",
               [.init("gin", 50, imperial: .oz(2)), .init("tonic", 150, imperial: .oz(6))], highball, garnish: "Add a lime wedge."),
        recipe("martini", "Dry Martini", "Botanical, cold, and wonderfully spare.", "Gin", "Coupe", "clear",
               [.init("gin", 60, imperial: .oz(2)), .init("dry-vermouth", 10, imperial: .tsp(2))], stir, garnish: "Add a lemon twist or an olive.", variations: [
                Variation(id: "orange", name: "A citrus accent", note: "One dash of orange bitters adds a subtle citrus note.", ingredients: [.init("gin", 60, imperial: .oz(2)), .init("dry-vermouth", 10, imperial: .tsp(2)), .init("orange-bitters", 1, .dash)])]),
        recipe("clover-club", "Clover Club", "Raspberry and lemon under a soft pink foam.", "Gin", "Coupe", "pink",
               [.init("gin", 50, imperial: .oz(2)), .init("lemon", 25, imperial: .oz(0.75)), .init("raspberry-syrup", 20, imperial: .oz(0.75)), .init("egg-white", 20, imperial: .oz(0.75))],
               ["Add all ingredients to a shaker without ice. Use pasteurized egg white, or aquafaba for egg-free foam.", "Seal firmly and shake for 15 seconds to build foam.", "Add ice and shake again for 10–15 seconds, then fine-strain into a chilled coupe."],
               garnish: "Add a raspberry to each glass.", variations: [
                Variation(id: "egg-free", name: "Egg-free foam", note: "Replace egg white with the same volume of aquafaba (unsalted chickpea brine). Use the same shaking method.", ingredients: [.init("gin", 50, imperial: .oz(2)), .init("lemon", 25, imperial: .oz(0.75)), .init("raspberry-syrup", 20, imperial: .oz(0.75)), .init("aquafaba", 20, imperial: .oz(0.75))])]),
        recipe("white-lady", "White Lady", "A crisp gin sour with a bright orange edge.", "Gin", "Coupe", "lemon",
               [.init("gin", 40, imperial: .oz(1.5)), .init("triple-sec", 30, imperial: .oz(1)), .init("lemon", 20, imperial: .oz(0.75))], shake,
               garnish: "Add a lemon twist. This version is made without egg white."),
        recipe("gin-and-it", "Gin & It", "Gin and Italian sweet vermouth, simply stirred.", "Gin", "Coupe", "amber",
               [.init("gin", 50, imperial: .oz(2)), .init("sweet-vermouth", 25, imperial: .oz(1))], stir,
               garnish: "Add an orange twist.", variations: [
                Variation(id: "orange", name: "A dash of orange", note: "Add one dash of orange bitters per drink to lift the vermouth’s citrus notes.", ingredients: [.init("gin", 50, imperial: .oz(2)), .init("sweet-vermouth", 25, imperial: .oz(1)), .init("orange-bitters", 1, .dash)])]),
        recipe("french-75", "French 75", "Gin, lemon, and a sparkling finish.", "Gin", "Wine", "lemon",
               [.init("gin", 30, imperial: .oz(1)), .init("lemon", 15, imperial: .oz(0.5)), .init("syrup", 10, imperial: .tsp(2)), .init("prosecco", 60, imperial: .oz(2))],
               ["Shake gin, lemon juice, and simple syrup with ice for 10–15 seconds.", "Strain into a chilled wine glass.", "Top with chilled dry Prosecco and stir gently. Dry Champagne is the traditional choice and can replace the Prosecco in the same amount; never shake sparkling wine."],
               garnish: "Add a lemon twist."),
        recipe("aviation", "Aviation", "Floral violet with tart lemon and cherry.", "Gin", "Coupe", "pink",
               [.init("gin", 45, imperial: .oz(1.5)), .init("maraschino", 15, imperial: .oz(0.5)), .init("lemon", 15, imperial: .oz(0.5)), .init("violette", 5, imperial: .tsp(1))], shake,
               garnish: "Add a cocktail cherry."),
        recipe("last-word", "Last Word", "Equal parts gin, herbs, cherry, and lime.", "Gin", "Coupe", "lime",
               [.init("gin", 22.5, imperial: .oz(0.75)), .init("green-chartreuse", 22.5, imperial: .oz(0.75)), .init("maraschino", 22.5, imperial: .oz(0.75)), .init("lime", 22.5, imperial: .oz(0.75))], shake),
        recipe("bramble", "Bramble", "A lemony gin sour with a blackberry drizzle.", "Gin", "Rocks", "pink",
               [.init("gin", 50, imperial: .oz(2)), .init("lemon", 25, imperial: .oz(1)), .init("syrup", 12.5, imperial: .oz(0.5)), .init("mure", 15, imperial: .oz(0.5))],
               ["Shake gin, lemon juice, and simple syrup with ice for 10–15 seconds.", "Strain into a rocks glass filled with crushed ice.", "Slowly drizzle the crème de mûre over the ice so it runs through the drink."],
               garnish: "Add a blackberry and a lemon slice."),
        recipe("southside", "Southside", "Fresh mint gives gin and lime a cool finish.", "Gin", "Coupe", "lime",
               [.init("gin", 60, imperial: .oz(2)), .init("lime", 25, imperial: .oz(0.75)), .init("syrup", 20, imperial: .oz(0.75)), .init("mint", 6, .leaf)],
               ["Gently press the mint with lime juice and simple syrup in a shaker.", "Add gin and ice, then shake for 10–15 seconds.", "Fine-strain into a chilled coupe to remove the mint fragments."],
               garnish: "Add a small mint leaf."),
        recipe("gin-basil-smash", "Gin Basil Smash", "A fresh basil sour with plenty of lemon.", "Gin", "Rocks", "lime",
               [.init("gin", 60, imperial: .oz(2)), .init("lemon", 30, imperial: .oz(1)), .init("syrup", 20, imperial: .oz(0.75)), .init("basil", 10, .leaf)],
               ["Muddle basil with lemon juice and simple syrup in a shaker to release its aroma.", "Add gin and ice, then shake hard for 10–15 seconds.", "Fine-strain into a rocks glass over fresh ice."],
               garnish: "Add a basil sprig."),
        recipe("hanky-panky", "Hanky Panky", "Sweet vermouth with a bitter herbal finish.", "Gin", "Coupe", "amber",
               [.init("gin", 45, imperial: .oz(1.5)), .init("sweet-vermouth", 45, imperial: .oz(1.5)), .init("fernet", 2.5, imperial: .tsp(0.5))], stir,
               garnish: "Express an orange peel over each glass."),
        recipe("corpse-reviver-2", "Corpse Reviver No. 2", "Lemon, orange, and a hint of anise.", "Gin", "Coupe", "lemon",
               [.init("gin", 25, imperial: .oz(0.75)), .init("triple-sec", 25, imperial: .oz(0.75)), .init("lillet-blanc", 25, imperial: .oz(0.75)), .init("lemon", 25, imperial: .oz(0.75)), .init("absinthe", 5, imperial: .tsp(1))],
               ["Rinse each chilled coupe with its share of the measured absinthe, swirling to coat the inside. Discard the excess.", "Shake gin, orange liqueur, Lillet Blanc, and lemon juice with ice for 10–15 seconds.", "Strain into the prepared coupe."],
               garnish: "Add an orange twist."),
        recipe("martinez", "Martinez", "Gin and sweet vermouth with a touch of cherry.", "Gin", "Coupe", "amber",
               [.init("gin", 45, imperial: .oz(1.5)), .init("sweet-vermouth", 45, imperial: .oz(1.5)), .init("maraschino", 5, imperial: .tsp(1)), .init("orange-bitters", 2, .dash)], stir,
               garnish: "Express a lemon twist over each glass."),
        recipe("manhattan", "Manhattan", "Spiced rye with a velvet finish.", "Whiskey", "Coupe", "red",
               [.init("rye", 60, imperial: .oz(2)), .init("sweet-vermouth", 30, imperial: .oz(1)), .init("angostura", 2, .dash)], stir,
               garnish: "Add a cocktail cherry.", variations: [
                Variation(id: "bourbon", name: "Bourbon Manhattan", note: "Use bourbon in place of rye for a rounder, sweeter whiskey profile.", ingredients: [.init("bourbon", 60, imperial: .oz(2)), .init("sweet-vermouth", 30, imperial: .oz(1)), .init("angostura", 2, .dash)])]),
        recipe("boulevardier", "Boulevardier", "The Negroni’s whiskey cousin.", "Whiskey", "Rocks", "red",
               [.init("bourbon", 45, imperial: .oz(1.5)), .init("campari", 30, imperial: .oz(1)), .init("sweet-vermouth", 30, imperial: .oz(1))],
               ["Stir all ingredients with ice in a mixing glass for 20–30 seconds.", "Strain into a rocks glass over a large ice cube."], garnish: "Add an orange peel.", variations: [
                Variation(id: "rye", name: "Rye Boulevardier", note: "Use rye whiskey instead of bourbon for a drier drink with more spice. Keep the Campari and sweet vermouth.", ingredients: [.init("rye", 45, imperial: .oz(1.5)), .init("campari", 30, imperial: .oz(1)), .init("sweet-vermouth", 30, imperial: .oz(1))])]),
        recipe("americano", "Americano", "Bitter orange, vermouth, and bubbles.", "Aperitif", "Highball", "red",
               [.init("campari", 30, imperial: .oz(1)), .init("sweet-vermouth", 30, imperial: .oz(1)), .init("soda", 90, imperial: .oz(3))], highball, garnish: "Add an orange slice."),
        recipe("aperol-spritz", "Aperol Spritz", "A little Italian sunshine.", "Aperitif", "Wine", "orange",
               [.init("prosecco", 90, imperial: .oz(3)), .init("aperol", 60, imperial: .oz(2)), .init("soda", 30, imperial: .oz(1))],
               ["Fill a wine glass with ice.", "Pour in prosecco, Aperol, and soda water.", "Give it one gentle stir."], garnish: "Add an orange slice."),
        recipe("mojito", "Mojito", "Fresh mint, lime, and a long pour.", "Rum", "Highball", "lime",
               [.init("rum", 50, imperial: .oz(2)), .init("lime", 25, imperial: .oz(0.75)), .init("syrup", 20, imperial: .oz(0.75)), .init("mint", 8, .leaf), .init("soda", 90, imperial: .oz(3))],
               ["Gently press the mint with lime juice and syrup in a tall glass; do not shred the leaves.", "Add rum and fill the glass with ice.", "Top with soda water and stir gently."], garnish: "Add a fresh mint sprig."),
        recipe("cuba-libre", "Cuba Libre", "Rum and cola with a proper lime squeeze.", "Rum", "Highball", "amber",
               [.init("rum", 50, imperial: .oz(2)), .init("lime", 15, imperial: .oz(0.5)), .init("cola", 120, imperial: .oz(4))], highball, garnish: "Add a lime wedge."),
        recipe("dark-stormy", "Dark Rum & Ginger", "Rich rum, fiery ginger, fresh lime.", "Rum", "Highball", "amber",
               [.init("dark-rum", 50, imperial: .oz(2)), .init("lime", 15, imperial: .oz(0.5)), .init("ginger-beer", 120, imperial: .oz(4))], highball),
        recipe("moscow-mule", "Moscow Mule", "Ginger heat with a citrus kick.", "Vodka", "Highball", "lemon",
               [.init("vodka", 50, imperial: .oz(2)), .init("lime", 15, imperial: .oz(0.5)), .init("ginger-beer", 120, imperial: .oz(4))], highball, garnish: "Add a lime wheel."),
        recipe("cosmopolitan", "Cosmopolitan", "Tart cranberry with a blush of orange.", "Vodka", "Coupe", "pink",
               [.init("vodka", 40, imperial: .oz(1.5)), .init("triple-sec", 15, imperial: .oz(0.5)), .init("lime", 15, imperial: .oz(0.5)), .init("cranberry", 30, imperial: .oz(1))], shake,
               garnish: "Express an orange peel over each glass."),
        recipe("espresso-martini", "Espresso Martini", "A rich little pick-me-up.", "Vodka", "Coupe", "coffee",
               [.init("vodka", 50, imperial: .oz(2)), .init("coffee-liqueur", 25, imperial: .oz(1)), .init("espresso", 30, imperial: .oz(1)), .init("syrup", 5, imperial: .tsp(1))],
               ["Let freshly brewed espresso cool briefly.", "Add all ingredients to a shaker filled with ice and shake hard for 15 seconds.", "Fine-strain into a chilled coupe."], garnish: "Add three coffee beans to each glass."),
        recipe("black-russian", "Black Russian", "Coffee and vodka, simply stirred.", "Vodka", "Rocks", "coffee",
               [.init("vodka", 50, imperial: .oz(2)), .init("coffee-liqueur", 25, imperial: .oz(1))],
               ["Fill a rocks glass with ice.", "Add vodka and coffee liqueur, then stir until cold."]),
        recipe("paloma", "Fresh Paloma", "Grapefruit and tequila, tall and bright.", "Tequila", "Highball", "pink",
               [.init("tequila", 50, imperial: .oz(2)), .init("grapefruit", 60, imperial: .oz(2)), .init("lime", 15, imperial: .oz(0.5)), .init("agave", 10, imperial: .tsp(2)), .init("soda", 60, imperial: .oz(2))],
               ["Add tequila, grapefruit, lime, and agave to a tall glass and stir.", "Fill with ice, add soda water, and stir gently."], garnish: "Add a grapefruit wedge and an optional salt rim."),
        recipe("sidecar", "Sidecar", "Brandy with a bright orange edge.", "Brandy", "Coupe", "orange",
               [.init("brandy", 50, imperial: .oz(2)), .init("triple-sec", 25, imperial: .oz(1)), .init("lemon", 25, imperial: .oz(1))], shake, garnish: "Add an orange twist; a half sugar rim is optional."),
        recipe("screwdriver", "Screwdriver", "Fresh orange with an easy pour.", "Vodka", "Highball", "orange",
               [.init("vodka", 50, imperial: .oz(2)), .init("orange", 120, imperial: .oz(4))], highball),
        recipe("mint-lemon-fizz", "Mint Lemon Fizz", "Fresh, sparkling, and alcohol-free.", "Alcohol-free", "Highball", "lemon",
               [.init("lemon", 30, imperial: .oz(1)), .init("syrup", 20, imperial: .oz(0.75)), .init("mint", 6, .leaf), .init("soda", 120, imperial: .oz(4))],
               ["Gently press mint with lemon juice and simple syrup in a tall glass.", "Fill with ice, add soda water, and stir gently."], garnish: "Add a lemon wheel.")
    ]
}
